{"time": "22:36:29", "level": "INFO", "message": "Попытка войти"}
{"time": "22:36:29", "level": "INFO", "message": "У Вас есть 3 попытки."}
{"time": "22:37:14", "level": "INFO", "message": "Попытка войти"}
{"time": "22:37:14", "level": "INFO", "message": "У Вас есть 3 попытки."}
{"time": "22:39:34", "level": "INFO", "message": "Попытка войти"}
{"time": "22:39:34", "level": "INFO", "message": "У Вас есть 3 попытки."}
{"time": "22:39:35", "level": "WARNING", "message": "Вы ввели пустой пароль."}
{"time": "22:39:42", "level": "ERROR", "message": "Войти не удалось, пароль неверный"}
{"time": "22:40:29", "level": "INFO", "message": "Попытка войти"}
{"time": "22:40:29", "level": "INFO", "message": "У Вас есть 3 попытки."}
{"time": "22:42:41", "level": "INFO", "message": "Попытка войти"}
{"time": "22:42:41", "level": "INFO", "message": "У Вас есть 3 попытки."}
{"time": "22:43:07", "level": "ERROR", "message": "Войти не удалось, пароль неверный"}
{"time": "22:44:04", "level": "INFO", "message": "Попытка войти"}
{"time": "22:44:04", "level": "INFO", "message": "У Вас есть 3 попытки."}
{"time": "22:44:10", "level": "ERROR", "message": "Некорректный символ"}
Traceback (most recent call last):
  File "/home/admin1/PycharmProjects/programm/mud6/task2/authentication.py", line 52, in input_and_check_password
    hasher.update(password.encode("latin-1"))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-5: ordinal not in range(256)
{"time": "22:44:36", "level": "WARNING", "message": "Содержит слово"}
{"time": "22:44:45", "level": "ERROR", "message": "Войти не удалось, пароль неверный"}
{"time": "22:55:07", "level": "INFO", "message": "Попытка войти"}
{"time": "22:55:07", "level": "INFO", "message": "У Вас есть 3 попытки."}
